name: "CD PIPELINE"

on: [push]
jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set environment variables
      run: |
        GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
        echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
    - name: Auth
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Deploy no APP Engine
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        promote: false
        version: ${{env.GIT_BRANCH}}
